### ISSUE TITLE
.Net Core support?

### ISSUE THREAD

**Issue by mattiasnordqvist** [alveflo/Commando#16]

**Comment by alveflo** [comment]
sure thang! feel free to submit a pull request, otherwise you have to wait until the summer is over haha

**Comment by allanpoulsen** [comment]
It compiles nicely under .Net Core :-)

**Comment by alveflo** [comment]
ah nice, thanks for confirming @allanpoulsen 👍 

closing this one, please reopen if you did encounter any issues with .net core @mattiasnordqvist
